import {TEST_RULES as R} from './test-rules.mjs';
import {computeCell,applyPassives,critChance} from './engine.mjs';
const mk=(stats,hp,hooks,spell,ward)=>({stats,hp,maxHp:stats.hp,h:applyPassives(hooks),spell,ward});
const ATTS={hp:100,atk:30,def:20,mag:24,spd:10,luck:8};const DEFS={hp:90,atk:26,def:18,mag:20,spd:9,luck:4};
const spell={powerBp:12000,effect:{kind:'none'}};
const A=(hooks=[],sp=spell)=>mk(ATTS,100,hooks,sp,null);const D=(hooks=[],ward=null)=>mk(DEFS,90,hooks,null,ward);
const row=(label,att,def,a,d)=>{const n=computeCell(R,att,def,a,d,false),c=computeCell(R,att,def,a,d,true);
 console.log(`| ${label} | ${a} | ${d} | ${n.toDef} | ${n.toAtt} | ${c.toDef} | ${c.toAtt} | ${n.healAtt}/${n.healDef} | ${n.tags.join(',')||'—'} | ${n.effectLands} |`);};
console.log('crit chance att', critChance(R,A()));
for(const a of ['attack','strike','spell'])for(const d of ['guard','counter','ward','open'])row('base',A(),D(),a,d);
row('strikeDmgBp+1000',A([{hook:'strikeDmgBp',value:1000}]),D(),'strike','ward');
row('guardVsStrike5000',A(),D([{hook:'guardVsStrikeBp',value:5000}]),'strike','guard');
row('counterDmg+2000',A(),D([{hook:'counterDmgBp',value:2000}]),'strike','counter');
row('spellTaken-2000',A(),D([{hook:'spellTakenBp',value:-2000}]),'spell','guard');
row('physTaken-5000',A(),D([{hook:'physTakenBp',value:-5000}]),'attack','ward');
row('barrier',A(),D([],R.wardSpells.shell),'spell','ward');
row('reflect',A(),D([],R.wardSpells['mirror-ward']),'spell','ward');
row('absorb',A(),D([],R.wardSpells.sponge),'spell','ward');
row('counterspell',A(),D([],R.wardSpells['null-ward']),'spell','ward');
row('counterspell',A(),D([],R.wardSpells['null-ward']),'attack','ward');
row('counterspell',A(),D([],R.wardSpells['null-ward']),'strike','ward');
row('wardReflect5000',A(),D([{hook:'wardReflectBp',value:5000}]),'spell','ward');
row('hex power0',A([],R.battleSpells.hex),D(),'spell','guard');
row('hex power0',A([],R.battleSpells.hex),D(),'spell','ward');
row('drain',A([],R.battleSpells.leech),D(),'spell','counter');
row('lifesteal2000',A([{hook:'lifestealBp',value:2000}]),D(),'attack','counter');
row('spellblade5000',A([{hook:'spellbladeStrike',value:5000}]),D(),'strike','guard');
row('spellblade5000',A([{hook:'spellbladeStrike',value:5000}]),D(),'strike','ward');
row('spellblade5000',A([{hook:'spellbladeStrike',value:5000}]),D(),'strike','counter');
row('min1',mk({...ATTS,atk:1},100,[],spell,null),D(),'attack','guard');
